### ISSUE TITLE
Merge Conflict

### ISSUE THREAD

**Issue by boddulurisrisai** [codewayy/github_series#86]
In master branch,I created a directory in that created new file **hello.txt**.After adding and commiting the file I created another branch name threshold and created a file which is named same as **hello.txt**.After add and commit .I switch back to master branch and updated the file.After adding and commiting the file when I try to merge threshold branch with master **Merge Conflict** occured.

![image](https://user-images.githubusercontent.com/32993841/86017390-9c87af80-ba41-11ea-92bb-89cb38d29323.png)

**Comment by boddulurisrisai** [comment]
**Resolving Merge Conflict**
Merge Conflict must be resolved manually.I go through the file which shows the conflict as
Hello everyone,I am srisai,I want to mess with this file
<<<<<<< HEAD
content to append
=======
totally different content 
>>>>>>> threshold
Here I edited the content as in the master as I felt it is right and added and commited the file and the conflict resolved.

![image](https://user-images.githubusercontent.com/32993841/86018758-68ad8980-ba43-11ea-9ccf-c9e332aff8d8.png)

**Comment by riya51** [comment]
Good work.
