### ISSUE TITLE
Merge_Conflict_issues

### ISSUE THREAD

**Issue by dhirajumate19** [codewayy/github_series#94]
First, I create a .txt file in the master branch and committed it.
after that I create a new branch i.e. Task and checkout to this branch and edited the .txt file and committed those changes .then I switch to the master branch and merge with Task branch and after that, I occurred merge conflict. 
![Conflict](https://user-images.githubusercontent.com/62473097/86087030-ca600900-bac0-11ea-8db7-0522f5cb4c81.png)

**Comment by muditgupta68** [comment]
Write method to resolve the merge conflict also
